apiVersion: v1
kind: Pod
metadata:
  name: spring-petclinic-rest
  labels:
    app: spring-petclinic-rest
spec:
  containers:
    - name: petclinic-rest-api
      image: springcommunity/spring-petclinic-rest
      resizePolicy:
      - resourceName: "cpu"
        restartPolicy: "RestartContainer"
      - resourceName: "memory"
        restartPolicy: "RestartContainer"
      ports:
        - containerPort: 9966 
      resources:
        limits:
          memory: "2Gi"
          cpu: "1000m"
        requests:
          memory: "2Gi"
          cpu: "1000m"
